name: EKS Stack Deployment

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        uses: bltavares/check-helm@v1.0.1
        with:
          path: ./argocd/apps

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          git archive -o eks-stack.zip HEAD
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: eks-stack
          path: eks-stack.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: eks-stack
      - name: Install AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli
      - name: Deploy
        run: |
          aws s3 cp eks-stack.zip s3://$AWS_S3_BUCKET/eks-stack.zip
